#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

# `without` is a remembered option - this can be removed once it's been deleted from all boxes
bundle config --delete without
bundle install --binstubs dev/gems/bin --path dev/gems

./node_modules/.bin/jspm registry create bower jspm-bower-endpoint -y
./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH
./node_modules/.bin/jspm registry export github

grunt --stack --no-color "$@"
